name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    
    steps:
    
    - name: checkout app-dev@master
      uses: actions/checkout@master
      with:
        repository: https://github.com/garettbass/app-dev
        fetch-depth: 1
        submodules: true
        
    - name: compile for C and C++
      run: sh app.c && sh app.cpp
