name: compile app for C and C++
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    steps:
    - name: checkout app-dev@master
      uses: actions/checkout@v1
      with:
        repository: garettbass/app-dev
        ref: master
        submodules: true
    - name: compile for C
      run: sh -c 'CC=gcc sh app.c -v'
    - name: compile for C++
      run: sh -c 'CC=gcc sh app.cpp -v'
